"""Generate the synthetic observation dataset.

The demo fixtures from PHASE 1 are hand-written and too small to exercise
anomaly detection. This script emits a larger dataset with **deliberately
planted** patterns, so every detector has a target it is supposed to find and
a control it is supposed to ignore.

It is synthetic and says so. Nothing here describes a real token, and the
addresses are DEMO placeholders. The script is committed so the dataset can be
regenerated byte-for-byte: no randomness, only fixed arithmetic.

    python scripts/generate_demo_timeseries.py

Planted patterns (what each token is for):

    SURGE  volume acceleration at hour 12, buyers rise with it
    DRAIN  liquidity withdrawn (-62%) at hour 15
    WHALE  top-10 concentration jumps 0.28 -> 0.71 at hour 9
    BUZZ   social mentions x8 at hour 10, on-chain participation flat
    FLAT   control. nothing happens. must produce zero anomalies
    OLD    seven days old, alive, low volume throughout
"""

from __future__ import annotations

import json
from datetime import UTC, datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "fixtures" / "timeseries.json"

START = datetime(2026, 8, 19, 12, 0, tzinfo=UTC)
HOURS = 24


def iso(moment: datetime) -> str:
    return moment.isoformat().replace("+00:00", "Z")


def address(tag: str) -> str:
    return f"DEMO{tag}{'x' * (40 - len(tag))}"


def snapshot(
    moment: datetime,
    *,
    liquidity: float,
    volume: float,
    holders: int,
    concentration: float,
    buys: int,
    sells: int,
    age_seconds: int,
) -> dict:
    return {
        "observed_at": iso(moment),
        "market_cap_usd": round(liquidity * 5.2, 2),
        "liquidity_usd": round(liquidity, 2),
        "volume_usd": round(volume, 2),
        "holders": holders,
        "holder_concentration_top10": round(concentration, 4),
        "transactions": buys + sells,
        "buys": buys,
        "sells": sells,
        "age_seconds": age_seconds,
    }


def build_token(
    tag: str,
    symbol: str,
    *,
    note: str,
    launch_offset_hours: int = 0,
    base_liquidity: float = 60_000.0,
    base_volume: float = 8_000.0,
    base_holders: int = 500,
    holder_growth: int = 14,
    base_concentration: float = 0.28,
    volume_multiplier_at: tuple[int, float] | None = None,
    liquidity_drop_at: tuple[int, float] | None = None,
    concentration_jump_at: tuple[int, float] | None = None,
) -> dict:
    launch = START - timedelta(hours=launch_offset_hours)
    snapshots = []

    liquidity = base_liquidity
    holders = base_holders
    concentration = base_concentration

    for hour in range(HOURS):
        moment = START + timedelta(hours=hour)

        # A gentle deterministic wobble, so the baseline is not a flat line
        # that any change would tower over.
        wobble = 1.0 + ((hour * 37) % 11 - 5) / 100.0
        volume = base_volume * wobble
        liquidity = liquidity * (1.0 + ((hour * 17) % 7 - 3) / 400.0)

        if volume_multiplier_at and hour >= volume_multiplier_at[0]:
            volume *= volume_multiplier_at[1]
        if liquidity_drop_at and hour == liquidity_drop_at[0]:
            liquidity *= liquidity_drop_at[1]
        if concentration_jump_at and hour >= concentration_jump_at[0]:
            concentration = concentration_jump_at[1]

        buy_share = 0.52 if not volume_multiplier_at or hour < volume_multiplier_at[0] else 0.63
        transactions = max(12, int(volume / 45))
        buys = int(transactions * buy_share)
        sells = transactions - buys

        holders += holder_growth if hour < 20 else holder_growth // 2
        if volume_multiplier_at and hour >= volume_multiplier_at[0]:
            holders += holder_growth * 2

        snapshots.append(
            snapshot(
                moment,
                liquidity=liquidity,
                volume=volume,
                holders=holders,
                concentration=concentration,
                buys=buys,
                sells=sells,
                age_seconds=int((moment - launch).total_seconds()),
            )
        )

    return {
        "address": address(tag),
        "symbol": symbol,
        "name": f"demo {symbol.lower()}",
        "decimals": 6,
        "launchpad": "demo-launchpad",
        "launch_time": iso(launch),
        "note": note,
        "snapshots": snapshots,
    }


def build_posts() -> tuple[list[dict], list[dict]]:
    accounts = [
        {
            "external_id": f"demo-ts-acct-{index}",
            "handle": f"demo_voice_{index}",
            "display_name": f"demo voice {index}",
            "followers": 200 * (index + 1),
            "account_created_at": iso(START - timedelta(days=200 - index * 30)),
        }
        for index in range(6)
    ]

    posts: list[dict] = []
    counter = 0

    def add(moment: datetime, account: int, token_tag: str, text: str, terms: list[str]) -> None:
        nonlocal counter
        counter += 1
        posts.append(
            {
                "external_id": f"demo-ts-post-{counter}",
                "account_external_id": f"demo-ts-acct-{account}",
                "posted_at": iso(moment),
                "text": text,
                "lang": "en",
                "likes": (counter * 7) % 40,
                "reposts": (counter * 3) % 11,
                "replies": counter % 5,
                "matched_terms": terms,
                "mentions_token_address": address(token_tag),
            }
        )

    # Baseline chatter: two posts an hour spread over the accounts.
    for hour in range(HOURS):
        moment = START + timedelta(hours=hour)
        add(moment, hour % 6, "SURGE", "some volume on SURGE today", ["memecoin", "Solana"])
        add(
            moment + timedelta(minutes=20),
            (hour + 2) % 6,
            "FLAT",
            "FLAT is still doing nothing",
            ["memecoin"],
        )

    # BUZZ: mentions multiply from hour 10 while on-chain stays flat.
    for hour in range(HOURS):
        moment = START + timedelta(hours=hour)
        mentions = 1 if hour < 10 else 8
        for index in range(mentions):
            add(
                moment + timedelta(minutes=3 * index),
                (hour + index) % 6,
                "BUZZ",
                "BUZZ is all over my timeline",
                ["memecoin", "AI agent", "meme narrative"],
            )

    return accounts, posts


def main() -> int:
    tokens = [
        build_token(
            "SURGE",
            "SURGE",
            note="planted: volume acceleration from hour 12",
            volume_multiplier_at=(12, 6.0),
        ),
        build_token(
            "DRAIN",
            "DRAIN",
            note="planted: liquidity drop at hour 15",
            liquidity_drop_at=(15, 0.38),
        ),
        build_token(
            "WHALE",
            "WHALE",
            note="planted: concentration jump at hour 9",
            concentration_jump_at=(9, 0.71),
        ),
        build_token(
            "BUZZ",
            "BUZZ",
            note="planted: social spike without on-chain participation",
            base_volume=5_000.0,
            holder_growth=4,
        ),
        build_token(
            "FLAT",
            "FLAT",
            note="control: nothing happens. detectors must stay silent",
            base_volume=3_000.0,
            holder_growth=3,
        ),
        build_token(
            "OLD",
            "OLD",
            note="planted: seven days old, still liquid, low volume",
            launch_offset_hours=24 * 7,
            base_volume=1_200.0,
            holder_growth=2,
        ),
    ]

    accounts, posts = build_posts()

    payload = {
        "_meta": {
            "is_demo": True,
            "synthetic": True,
            "generated_by": "scripts/generate_demo_timeseries.py",
            "note": (
                "Synthetic time series with deliberately planted patterns, used to "
                "exercise the observation pipeline. Deterministic: regenerating the "
                "file reproduces it exactly. Describes no real token, wallet or account."
            ),
            "window_start": iso(START),
            "window_end": iso(START + timedelta(hours=HOURS - 1)),
            "hours": HOURS,
            "dataset_version": "demo-timeseries-1",
        },
        "tokens": tokens,
        "accounts": accounts,
        "posts": posts,
    }

    OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(
        f"wrote {OUT.relative_to(ROOT)}: {len(tokens)} tokens x {HOURS}h, "
        f"{len(posts)} posts, {len(accounts)} accounts"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
