"""Vocabulary shared by the database, the API schemas and the frontend.

These strings are part of the public contract: the terminal, the trace
viewer and the research pages all key off them.
"""

from __future__ import annotations

from enum import StrEnum


class HypothesisStatus(StrEnum):
    PROPOSED = "PROPOSED"
    TESTING = "TESTING"
    SUPPORTED = "SUPPORTED"
    REJECTED = "REJECTED"
    INCONCLUSIVE = "INCONCLUSIVE"


class ExperimentStatus(StrEnum):
    PLANNED = "PLANNED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ABANDONED = "ABANDONED"


class CriticVerdict(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    NEEDS_MORE_DATA = "NEEDS_MORE_DATA"


class ResultOutcome(StrEnum):
    SUPPORTED = "SUPPORTED"
    REJECTED = "REJECTED"
    INCONCLUSIVE = "INCONCLUSIVE"


class MemoryType(StrEnum):
    OBSERVATION = "OBSERVATION"
    HYPOTHESIS = "HYPOTHESIS"
    EXPERIMENT = "EXPERIMENT"
    RESULT = "RESULT"
    FAILURE = "FAILURE"
    PATTERN = "PATTERN"
    NARRATIVE = "NARRATIVE"
    TOKEN = "TOKEN"
    WALLET = "WALLET"
    SOCIAL_EVENT = "SOCIAL_EVENT"
    SOURCE = "SOURCE"


class AnomalyType(StrEnum):
    VOLUME_ACCELERATION = "VOLUME_ACCELERATION"
    HOLDER_ACCELERATION = "HOLDER_ACCELERATION"
    LIQUIDITY_CHANGE = "LIQUIDITY_CHANGE"
    SOCIAL_VELOCITY = "SOCIAL_VELOCITY"
    SOCIAL_ONCHAIN_DIVERGENCE = "SOCIAL_ONCHAIN_DIVERGENCE"
    WALLET_CONCENTRATION_CHANGE = "WALLET_CONCENTRATION_CHANGE"
    NEW_WALLET_CLUSTER = "NEW_WALLET_CLUSTER"
    UNUSUAL_TRANSACTION_PATTERN = "UNUSUAL_TRANSACTION_PATTERN"
    NARRATIVE_ACCELERATION = "NARRATIVE_ACCELERATION"
    TOKEN_SURVIVAL_ANOMALY = "TOKEN_SURVIVAL_ANOMALY"
    QUOTE_ASSET_PAIRING = "QUOTE_ASSET_PAIRING"


class ObservationKind(StrEnum):
    ONCHAIN = "ONCHAIN"
    SOCIAL = "SOCIAL"
    DERIVED = "DERIVED"


class ContentType(StrEnum):
    OBSERVATION = "OBSERVATION"
    HYPOTHESIS = "HYPOTHESIS"
    EXPERIMENT = "EXPERIMENT"
    RESULT = "RESULT"
    FAILURE = "FAILURE"
    DISCOVERY = "DISCOVERY"
    THOUGHT = "THOUGHT"


class DraftStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PUBLISHED = "PUBLISHED"


class AgentName(StrEnum):
    OBSERVER = "observer"
    RESEARCHER = "researcher"
    DATA_SCIENTIST = "data_scientist"
    CRITIC = "critic"
    WRITER = "writer"
    REVIEWER = "reviewer"


class SystemState(StrEnum):
    """Drives the central visualization. Must reflect real system state."""

    IDLE = "IDLE"
    OBSERVING = "OBSERVING"
    ANALYZING = "ANALYZING"
    HYPOTHESIZING = "HYPOTHESIZING"
    TESTING = "TESTING"
    REJECTED = "REJECTED"
    SUPPORTED = "SUPPORTED"
    LEARNING = "LEARNING"


class EventType(StrEnum):
    SYSTEM_START = "SYSTEM_START"
    OBSERVATION = "OBSERVATION"
    ANOMALY = "ANOMALY"
    MEMORY_SEARCH = "MEMORY_SEARCH"
    HYPOTHESIS_CREATED = "HYPOTHESIS_CREATED"
    EXPERIMENT_STARTED = "EXPERIMENT_STARTED"
    EXPERIMENT_PROGRESS = "EXPERIMENT_PROGRESS"
    EXPERIMENT_COMPLETED = "EXPERIMENT_COMPLETED"
    CRITIC_RESULT = "CRITIC_RESULT"
    HYPOTHESIS_REJECTED = "HYPOTHESIS_REJECTED"
    HYPOTHESIS_SUPPORTED = "HYPOTHESIS_SUPPORTED"
    MEMORY_UPDATED = "MEMORY_UPDATED"
    DRAFT_CREATED = "DRAFT_CREATED"
    DRAFT_REVIEWED = "DRAFT_REVIEWED"
    AGENT_RUN = "AGENT_RUN"
    ERROR = "ERROR"


class TraceStepKind(StrEnum):
    OBSERVATION = "OBSERVATION"
    ANOMALY = "ANOMALY"
    MEMORY_SEARCH = "MEMORY_SEARCH"
    HYPOTHESIS = "HYPOTHESIS"
    DATASET = "DATASET"
    EXPERIMENT = "EXPERIMENT"
    CRITIC = "CRITIC"
    RESULT = "RESULT"
    MEMORY_UPDATE = "MEMORY_UPDATE"
